version: '3'

services:
  web:
    container_name: django-web
    build: "./django"
    volumes:
      - ./django/code:/code
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    container_name: django-db
    environment:
      - MYSQL_DATABASE=django-docker-db
      - MYSQL_USER=django
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    hostname: mysql
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql