version: '3'

services:
  web:
    container_name: django-web
    build: "./django"
    volumes:
      - ./django/code:/code
    ports:
      - ${WEB_PORT-8000}:8000
    tty: true
    depends_on:
      - db
  db:
    image: mysql:${DB_VERSION-8.0}
    restart: always
    container_name: django-db
    environment:
      - MYSQL_DATABASE=${DB_DATABASE-default}
      - MYSQL_USER=${DB_USER-default}
      - MYSQL_PASSWORD=${DB_PASSWORD-secret}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD-secret}
      - TZ=${TZ-Asia/Tokyo}
    hostname: mysql
    ports:
      - "${DB_PORT-3306}:3306"
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql